docker-compose:
  generator: lgtm
  files:
    - ../docker-compose.oats.yml
input:
  - path: /api/MsSql/Tables
expected:
  traces:
    - traceql: '{ name =~ "api/MsSql/Tables"}'
      spans:
        - name: 'master'
          attributes:
            db.system: mssql
            db.statement_type: Text
            otel.library.name: OpenTelemetry.Instrumentation.SqlClient
